from agents import (
    Agent,
    Runner,
    OpenAIChatCompletionsModel,
    function_tool,
    handoff,
    set_tracing_disabled,
)
import asyncio
import os
import sys
from dotenv import load_dotenv
import openai

# Ensure UTF-8 output on Windows console
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

load_dotenv(override=True)

# Remove OPENAI_API_KEY so the Agents SDK does not attempt OpenAI tracing (prevents 429 errors)
os.environ.pop("OPENAI_API_KEY", None)
set_tracing_disabled(True)

# Setup Groq Async client
client = openai.AsyncOpenAI(
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ.get("GROQ_API_KEY"),
)

model = OpenAIChatCompletionsModel(
    model="qwen/qwen3.6-27b",
    openai_client=client,
)

# -------------------------------------------------------------------------
# 1. Define a tool
# -------------------------------------------------------------------------
@function_tool
def get_weather(city: str) -> str:
    """Get the current weather for a city."""
    return f"The weather in {city} is 22°C, sunny with a gentle breeze."

# -------------------------------------------------------------------------
# 2. Define Specialist & Triage Agents
# -------------------------------------------------------------------------
weather_agent = Agent(
    name="Weather Agent",
    handoff_description="Handles weather information queries.",
    instructions="You provide friendly and concise weather reports. Use get_weather tool.",
    tools=[get_weather],
    model=model,
)

weather_handoff = handoff(weather_agent)
# Sanitize schema for Groq compatibility
weather_handoff.input_json_schema.pop("required", None)

triage_agent = Agent(
    name="Triage Agent",
    instructions="You are a helpful assistant. Route weather-related questions to the Weather Agent, or answer general questions directly.",
    handoffs=[weather_handoff],
    model=model,
)

# -------------------------------------------------------------------------
# 3. Streaming Runner Example
# -------------------------------------------------------------------------
async def stream_conversation(user_prompt: str):
    print(f"\n💬 User: {user_prompt}\n")
    print("🤖 Agent (Streaming): ", end="", flush=True)

    # Runner.run_streamed returns a RunResultStreaming object
    result = Runner.run_streamed(triage_agent, user_prompt)

    # Iterate over streaming events in real time
    async for event in result.stream_events():
        # A. Agent switch / Handoff event
        if event.type == "agent_updated_stream_event":
            print(f"\n\n🔀 [Handoff] Switched to agent: {event.new_agent.name}")
            print(f"🤖 {event.new_agent.name}: ", end="", flush=True)

        # B. High-level run item events (tools called, tool outputs, etc.)
        elif event.type == "run_item_stream_event":
            if event.name == "tool_called":
                tool_name = getattr(event.item, "tool_name", "unknown")
                print(f"\n⚙️  [Tool Call] Executing: {tool_name}...")
            elif event.name == "tool_output":
                output = getattr(event.item, "output", "")
                print(f"✅ [Tool Result] -> {output}")
                print(f"🤖 Agent: ", end="", flush=True)

        # C. Raw token deltas from the model
        elif event.type == "raw_response_event":
            # event.data contains the text delta generated by the model
            if hasattr(event.data, "delta") and event.data.delta:
                print(event.data.delta, end="", flush=True)

    print("\n" + "-" * 50)
    print(f"✨ Final Answered By: {result.last_agent.name}")
    print("-" * 50)

async def main():
    # Example 1: Direct response with token streaming
    await stream_conversation("Explain what is quantum computing in 2 short sentences.")

    # Example 2: Streaming through a handoff and tool call
    await stream_conversation("What is the weather like in Tokyo right now?")

if __name__ == "__main__":
    asyncio.run(main())
